'use client'
import { useState, useTransition } from 'react'
import { CheckCircle2, Copy, LoaderCircle, Send } from 'lucide-react'
import { submitApplication } from '@/app/(candidate)/minha-area/inscricoes/[id]/actions'

export function CandidateApplicationSubmit({ applicationId, enabled, protocol, submittedAt }: { applicationId: string; enabled: boolean; protocol?: string | null; submittedAt?: string | null }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState(''); const [resultProtocol, setResultProtocol] = useState(protocol || '')
  if (resultProtocol) return <section className="mt-8 rounded-[24px] border border-[#8acbb4] bg-[#eaf8f2] p-5 sm:p-7"><div className="flex items-start gap-3"><CheckCircle2 className="mt-1 h-6 w-6 shrink-0 text-[#137052]" /><div><p className="text-sm font-extrabold uppercase tracking-[.14em] text-[#137052]">Inscrição enviada</p><h2 className="mt-2 font-display text-2xl font-extrabold text-[#142038]">Guarde seu protocolo</h2><div className="mt-4 flex flex-col gap-2 sm:flex-row sm:items-center"><code className="rounded-xl border border-[#a7d5c5] bg-white px-4 py-3 text-base font-black tracking-wider text-[#174f3e]">{resultProtocol}</code><button type="button" onClick={() => navigator.clipboard.writeText(resultProtocol)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 text-sm font-extrabold text-[#116c4e] hover:bg-white"><Copy className="h-4 w-4" /> Copiar</button></div>{submittedAt && <p className="mt-3 text-sm text-[#526b61]">Recebida em {new Date(submittedAt).toLocaleString('pt-BR')}.</p>}</div></div></section>
  return <form action={(formData) => startTransition(async () => { const result = await submitApplication(formData); setMessage(result.message); if (result.type === 'success' && result.protocol) setResultProtocol(result.protocol) })} className="mt-8 rounded-[24px] border border-[#d4c17f] bg-[#fff9e8] p-5 sm:p-7"><input type="hidden" name="applicationId" value={applicationId} /><p className="text-xs font-extrabold uppercase tracking-[.15em] text-[#765400]">Confirmação final</p><h2 className="mt-2 font-display text-2xl font-extrabold text-[#142038]">Leia e confirme antes de enviar</h2><div className="mt-5 space-y-3">{[['edital','Li e aceito as regras e a versão vigente do edital.'],['truthfulness','Declaro que as informações fornecidas são verdadeiras.'],['requirements','Confirmo que cumpro os requisitos das vagas escolhidas.'],['lgpd','Li o aviso de privacidade e autorizo o tratamento dos dados para este processo.']].map(([name,label]) => <label key={name} className="flex cursor-pointer items-start gap-3 rounded-xl border border-[#dfcf99] bg-white p-3.5 text-sm font-bold leading-6 text-[#35465b]"><input type="checkbox" name={name} required className="mt-1 h-4 w-4 shrink-0" />{label}</label>)}</div>{message && <p role="status" className="mt-4 text-sm font-bold text-[#8b3434]">{message}</p>}<button disabled={!enabled || pending} className="mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#16775a] px-5 text-sm font-extrabold text-white disabled:cursor-not-allowed disabled:opacity-45 sm:w-auto">{pending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}{pending ? 'Enviando...' : enabled ? 'Enviar inscrição definitivamente' : 'Conclua as pendências acima'}</button></form>
}
