'use client'

import { useState, useTransition } from 'react'
import { ArrowDown, ArrowUp, Check, LoaderCircle, Plus, Trash2 } from 'lucide-react'
import { saveApplicationPreferences } from '@/app/(candidate)/minha-area/inscricoes/[id]/actions'

export type CandidateVacancy = { id: string; title: string; municipality: string; modality: string; vacancyLabel: string }

export function CandidateVacancyPreferences({ applicationId, vacancies, initialIds, maxPreferences, locked }: { applicationId: string; vacancies: CandidateVacancy[]; initialIds: string[]; maxPreferences: number; locked: boolean }) {
  const [selected, setSelected] = useState(initialIds)
  const [feedback, setFeedback] = useState<{ type: 'success' | 'error'; message: string } | null>(null)
  const [pending, startTransition] = useTransition()
  const selectedVacancies = selected.map((id) => vacancies.find((item) => item.id === id)).filter(Boolean) as CandidateVacancy[]
  const available = vacancies.filter((item) => !selected.includes(item.id))
  const move = (index: number, delta: number) => setSelected((current) => { const next = [...current]; const target = index + delta; if (target < 0 || target >= next.length) return current; [next[index], next[target]] = [next[target], next[index]]; return next })
  const save = () => startTransition(async () => { const data = new FormData(); data.set('applicationId', applicationId); selected.forEach((id) => data.append('vacancyId', id)); const result = await saveApplicationPreferences(data); setFeedback({ type: result.status, message: result.message }) })

  return <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(320px,.72fr)]">
    <section className="rounded-[24px] border border-[#d9e0e7] bg-white p-5 sm:p-6"><h2 className="font-display text-xl font-bold text-[#172033]">Vagas disponíveis</h2><p className="mt-2 text-sm text-[#657084]">Adicione somente as opções em que deseja concorrer.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{available.map((vacancy) => <article key={vacancy.id} className="flex flex-col rounded-2xl border border-[#dce3e9] bg-[#f8fafb] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#137052]">{vacancy.modality}</p><h3 className="mt-2 font-bold text-[#172033]">{vacancy.title}</h3><p className="mt-2 text-sm text-[#657084]">{vacancy.municipality} · {vacancy.vacancyLabel}</p><button disabled={locked || selected.length >= maxPreferences} onClick={() => setSelected((current) => [...current, vacancy.id])} className="mt-4 inline-flex min-h-10 items-center justify-center gap-2 rounded-xl border border-[#9bcdbb] bg-white text-sm font-bold text-[#116c4e] disabled:cursor-not-allowed disabled:opacity-45"><Plus className="h-4 w-4" /> Adicionar</button></article>)}</div>{available.length === 0 && <p className="mt-5 rounded-2xl bg-[#f4f7f9] p-5 text-sm text-[#657084]">Todas as vagas disponíveis já foram adicionadas.</p>}</section>
    <aside className="h-fit rounded-[24px] border border-[#b9d9cd] bg-[#f1faf6] p-5 sm:p-6 lg:sticky lg:top-6"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-[.16em] text-[#137052]">Sua ordem de preferência</p><h2 className="mt-1 font-display text-xl font-bold text-[#172033]">{selected.length} de {maxPreferences}</h2></div></div><ol className="mt-5 space-y-3">{selectedVacancies.map((vacancy, index) => <li key={vacancy.id} className="rounded-2xl border border-[#cfe2da] bg-white p-4"><div className="flex gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#16775a] text-sm font-black text-white">{index + 1}</span><div className="min-w-0 flex-1"><p className="font-bold text-[#172033]">{vacancy.title}</p><p className="mt-1 text-xs text-[#657084]">{vacancy.municipality}</p></div></div>{!locked && <div className="mt-3 flex gap-2"><button aria-label="Subir preferência" disabled={index === 0} onClick={() => move(index, -1)} className="grid h-9 w-9 place-items-center rounded-lg border bg-white disabled:opacity-30"><ArrowUp className="h-4 w-4" /></button><button aria-label="Descer preferência" disabled={index === selected.length - 1} onClick={() => move(index, 1)} className="grid h-9 w-9 place-items-center rounded-lg border bg-white disabled:opacity-30"><ArrowDown className="h-4 w-4" /></button><button aria-label="Remover preferência" onClick={() => setSelected((current) => current.filter((id) => id !== vacancy.id))} className="ml-auto grid h-9 w-9 place-items-center rounded-lg border border-red-200 text-red-600"><Trash2 className="h-4 w-4" /></button></div>}</li>)}</ol>{selected.length === 0 && <p className="mt-5 rounded-2xl border border-dashed border-[#b9d9cd] p-5 text-sm text-[#657084]">Adicione pelo menos uma vaga para continuar.</p>}{feedback && <p role="status" className={`mt-4 rounded-xl p-3 text-sm font-semibold ${feedback.type === 'success' ? 'bg-white text-[#116c4e]' : 'bg-red-50 text-red-700'}`}>{feedback.message}</p>}<button disabled={locked || pending || selected.length === 0} onClick={save} className="mt-5 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#16775a] px-4 text-sm font-extrabold text-white disabled:cursor-not-allowed disabled:opacity-50">{pending ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Check className="h-4 w-4" />}{locked ? 'Inscrição bloqueada' : pending ? 'Salvando...' : 'Salvar opções'}</button></aside>
  </div>
}
