'use client'

import { useState, useTransition } from 'react'
import { Calculator, Loader2, RefreshCw } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { recalculateSigecApplicationScore } from '@/app/(dashboard)/sigec-candidaturas/[id]/actions'
import { formatSigecDate, type SigecAcademicProductionScore, type SigecConsolidatedScoreSnapshot, type SigecExperienceScore, type SigecPostgraduateScore } from '@/lib/sigec-application-detail'

export function SigecConsolidatedScoreControls({applicationId,applicationState,currentTotal,postgraduate,experience,academic,latestSnapshot}:{applicationId:string;applicationState:string;currentTotal:number|null;postgraduate:SigecPostgraduateScore;experience:SigecExperienceScore;academic:SigecAcademicProductionScore;latestSnapshot:SigecConsolidatedScoreSnapshot|null}) {
  const router=useRouter(); const [pending,startTransition]=useTransition(); const [feedback,setFeedback]=useState<{error:boolean;text:string}|null>(null); const preview=Number(postgraduate.points)+Number(experience.points)+Number(academic.points)
  function recalculate(){setFeedback(null);startTransition(async()=>{const result=await recalculateSigecApplicationScore({applicationId});setFeedback({error:Boolean(result.error),text:result.error||result.success||''});if(result.success)router.refresh()})}
  const parts=[['Pós-graduação',Number(postgraduate.points),30],['Experiência docente',Number(experience.points),40],['Produção e formação',Number(academic.points),30]] as const
  return <section className="overflow-hidden rounded-2xl" style={{background:'hsl(var(--card))',border:'1px solid hsl(var(--accent-blue) / .3)'}}><div className="grid lg:grid-cols-[.72fr_1.28fr]"><div className="flex flex-col justify-between gap-5 p-5 sm:p-6" style={{background:'linear-gradient(145deg,hsl(var(--accent-blue) / .14),hsl(var(--card)))'}}><div className="flex gap-3"><Calculator className="mt-1 h-5 w-5" style={{color:'hsl(var(--accent-blue))'}}/><div><p className="text-xs font-bold uppercase tracking-[.14em]" style={{color:'hsl(var(--fg3))'}}>Nota consolidada</p><p className="mt-2 font-data text-4xl font-bold" style={{color:'hsl(var(--fg1))'}}>{currentTotal===null?'—':Number(currentTotal)}<span className="text-lg font-medium" style={{color:'hsl(var(--fg3))'}}>/100</span></p></div></div><div><p className="text-xs" style={{color:'hsl(var(--fg3))'}}>{latestSnapshot?`Versão ${latestSnapshot.version} · ${latestSnapshot.algorithm_version} · ${formatSigecDate(latestSnapshot.created_at,true)}`:'Ainda não consolidada'}</p>{currentTotal!==preview&&<p className="mt-2 text-xs font-semibold" style={{color:'hsl(var(--accent-amber))'}}>As análises somam {preview} pontos. Consolide para atualizar a nota.</p>}</div></div><div className="p-5 sm:p-6"><div className="grid gap-3 sm:grid-cols-3">{parts.map(([label,value,max])=><div key={label} className="rounded-xl p-3" style={{background:'hsl(var(--muted) / .55)',border:'1px solid hsl(var(--border))'}}><p className="text-[11px] font-semibold" style={{color:'hsl(var(--fg3))'}}>{label}</p><p className="mt-2 font-data text-xl font-bold" style={{color:'hsl(var(--fg1))'}}>{value}<span className="text-xs font-medium" style={{color:'hsl(var(--fg3))'}}>/{max}</span></p></div>)}</div><button type="button" onClick={recalculate} disabled={pending||applicationState!=='submitted'} className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-lg px-4 text-sm font-bold disabled:opacity-50 sm:w-auto" style={{background:'hsl(var(--accent-blue))',color:'white'}}>{pending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<RefreshCw className="mr-2 h-4 w-4"/>}Consolidar nota</button>{feedback&&<p className="mt-3 rounded-lg px-3 py-2 text-sm" style={{background:feedback.error?'hsl(var(--accent-red) / .08)':'hsl(var(--accent-green) / .1)',color:feedback.error?'hsl(var(--accent-red))':'hsl(var(--accent-green))'}}>{feedback.text}</p>}</div></div></section>
}
