'use client'

import { useMemo, useState, useTransition } from 'react'
import { BriefcaseBusiness, CheckCircle2, Loader2, XCircle } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { reviewSigecExperienceEvidence } from '@/app/(dashboard)/sigec-candidaturas/[id]/actions'
import { formatSigecDate, type SigecApplicationDetail, type SigecExperienceReview, type SigecExperienceScore, type SigecTeachingExperience } from '@/lib/sigec-application-detail'

export function SigecExperienceScoringControls({ applicationId, applicationState, experience, reviews, score, documents }: { applicationId: string; applicationState: string; experience: SigecTeachingExperience[]; reviews: SigecExperienceReview[]; score: SigecExperienceScore; documents: SigecApplicationDetail['documents'] }) {
  const router=useRouter(); const [experienceId,setExperienceId]=useState(experience[0]?.id || ''); const [documentId,setDocumentId]=useState(''); const [reason,setReason]=useState(''); const [feedback,setFeedback]=useState<{error:boolean;text:string}|null>(null); const [pending,startTransition]=useTransition()
  const approvedDocuments=useMemo(()=>documents.filter((item)=>item.isCurrent&&!item.removedAt&&item.technicalStatus==='validated'&&item.malwareStatus==='clean'&&item.reviewStatus==='valid'),[documents])
  const latestReviews=useMemo(()=>new Map(reviews.map((item)=>[item.experience_id,item])),[reviews]); const disabled=applicationState!=='submitted'||!experienceId||!documentId||pending
  function submit(decision:'eligible'|'rejected'){setFeedback(null);startTransition(async()=>{const result=await reviewSigecExperienceEvidence({applicationId,experienceId,documentId,decision,publicReason:reason});setFeedback({error:Boolean(result.error),text:result.error||result.success||''});if(result.success){setReason('');router.refresh()}})}
  return <section className="overflow-hidden rounded-2xl" style={{background:'hsl(var(--card))',border:'1px solid hsl(var(--border))'}}>
    <header className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between" style={{borderBottom:'1px solid hsl(var(--border))'}}><div className="flex gap-3"><BriefcaseBusiness className="mt-0.5 h-5 w-5 shrink-0" style={{color:'hsl(var(--accent-blue))'}}/><div><h2 className="font-semibold" style={{color:'hsl(var(--fg1))'}}>Pontuação de experiência docente</h2><p className="mt-1 text-xs leading-5" style={{color:'hsl(var(--fg3))'}}>Períodos sobrepostos contam uma vez. A pontuação usa meses completos e fica limitada a 40 pontos.</p></div></div><div className="shrink-0 rounded-xl px-4 py-3 text-center" style={{background:'hsl(var(--accent-blue) / .1)',border:'1px solid hsl(var(--accent-blue) / .25)'}}><p className="font-data text-2xl font-bold" style={{color:'hsl(var(--accent-blue))'}}>{Number(score.points)}<span className="text-sm font-medium">/40</span></p><p className="text-[10px] font-bold uppercase tracking-wide" style={{color:'hsl(var(--fg3))'}}>{score.total_months} meses e {score.remaining_days} dias únicos</p></div></header>
    <div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_minmax(280px,.72fr)]"><div><h3 className="text-xs font-bold uppercase tracking-[.12em]" style={{color:'hsl(var(--fg3))'}}>Vínculos docentes</h3>{experience.length?<div className="mt-3 space-y-2">{experience.map((item)=>{const review=latestReviews.get(item.id);return <div key={item.id} className="rounded-xl p-3" style={{background:'hsl(var(--muted) / .55)',border:'1px solid hsl(var(--border))'}}><div className="flex flex-col gap-2 sm:flex-row sm:justify-between"><div><p className="text-sm font-semibold" style={{color:'hsl(var(--fg1))'}}>{item.role_title}</p><p className="mt-1 text-xs" style={{color:'hsl(var(--fg3))'}}>{item.institution} · {formatSigecDate(item.starts_on)} a {item.ends_on?formatSigecDate(item.ends_on):'atual'}</p></div><span className="shrink-0 text-xs font-bold" style={{color:review?.decision==='eligible'?'hsl(var(--accent-green))':review?.decision==='rejected'?'hsl(var(--accent-red))':'hsl(var(--fg3))'}}>{review?.decision==='eligible'?'Período aprovado':review?.decision==='rejected'?'Não aceito':'Não analisado'}</span></div>{review?.public_reason&&<p className="mt-2 text-xs leading-5" style={{color:'hsl(var(--fg2))'}}>Motivo: {review.public_reason}</p>}</div>})}</div>:<p className="mt-3 rounded-xl p-4 text-sm" style={{background:'hsl(var(--muted) / .55)',color:'hsl(var(--fg3))'}}>O candidato não informou experiência docente.</p>}</div>
      <div className="space-y-3"><label className="block text-xs font-semibold" style={{color:'hsl(var(--fg2))'}}>Vínculo<select value={experienceId} onChange={(e)=>setExperienceId(e.target.value)} disabled={pending||!experience.length} className="mt-2 min-h-11 w-full rounded-lg border bg-transparent px-3 text-sm" style={{borderColor:'hsl(var(--border))',color:'hsl(var(--fg1))'}}><option value="">Selecione</option>{experience.map((item)=><option key={item.id} value={item.id}>{item.role_title} — {item.institution}</option>)}</select></label><label className="block text-xs font-semibold" style={{color:'hsl(var(--fg2))'}}>Documento aprovado<select value={documentId} onChange={(e)=>setDocumentId(e.target.value)} disabled={pending||!approvedDocuments.length} className="mt-2 min-h-11 w-full rounded-lg border bg-transparent px-3 text-sm" style={{borderColor:'hsl(var(--border))',color:'hsl(var(--fg1))'}}><option value="">Selecione</option>{approvedDocuments.map((item)=><option key={item.documentId} value={item.documentId}>{item.requirementLabel} · versão {item.version}</option>)}</select></label>{!approvedDocuments.length&&<p className="text-xs leading-5" style={{color:'hsl(var(--accent-amber))'}}>Aprove primeiro o comprovante do vínculo.</p>}<label className="block text-xs font-semibold" style={{color:'hsl(var(--fg2))'}}>Motivo, somente se não aceitar<textarea value={reason} onChange={(e)=>setReason(e.target.value)} disabled={pending} maxLength={2000} rows={3} className="mt-2 w-full rounded-lg border bg-transparent p-3 text-sm" style={{borderColor:'hsl(var(--border))',color:'hsl(var(--fg1))'}}/></label><div className="grid gap-2 sm:grid-cols-2"><button type="button" onClick={()=>submit('eligible')} disabled={disabled||Boolean(reason.trim())} className="inline-flex min-h-11 items-center justify-center rounded-lg px-4 text-sm font-bold disabled:opacity-50" style={{background:'hsl(var(--accent-green))',color:'white'}}>{pending?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<CheckCircle2 className="mr-2 h-4 w-4"/>}Aprovar período</button><button type="button" onClick={()=>submit('rejected')} disabled={disabled||reason.trim().length<3} className="inline-flex min-h-11 items-center justify-center rounded-lg px-4 text-sm font-bold disabled:opacity-50" style={{background:'hsl(var(--accent-red))',color:'white'}}><XCircle className="mr-2 h-4 w-4"/>Não aceitar</button></div>{feedback&&<p className="rounded-lg px-3 py-2 text-sm" style={{background:feedback.error?'hsl(var(--accent-red) / .08)':'hsl(var(--accent-green) / .1)',color:feedback.error?'hsl(var(--accent-red))':'hsl(var(--accent-green))'}}>{feedback.text}</p>}</div>
    </div>
  </section>
}
