export const SIGEC_DEFAULT_STAGES = [
  { code: 'documentacao_pendente', label: 'Documentação pendente', publicDescription: 'Existem documentos ou informações que precisam ser corrigidos antes da continuidade da análise.', color: '#d97706', allowsAppeal: false, terminal: false, whatsappTemplate: 'Olá, {{nome}}. Sua candidatura em {{processo}} possui pendências. Acesse {{link}} para verificar os itens solicitados.' },
  { code: 'em_analise', label: 'Em análise', publicDescription: 'A candidatura e os documentos enviados estão em análise pela equipe responsável.', color: '#2563eb', allowsAppeal: false, terminal: false, whatsappTemplate: 'Olá, {{nome}}. Sua candidatura em {{processo}} está em análise. Acompanhe pelo SIGEC Processos: {{link}}.' },
  { code: 'habilitado', label: 'Habilitado', publicDescription: 'A documentação obrigatória foi validada e o candidato está apto a seguir no processo.', color: '#059669', allowsAppeal: false, terminal: false, whatsappTemplate: 'Olá, {{nome}}. Sua documentação foi validada e você está habilitado em {{processo}}. Acompanhe: {{link}}.' },
  { code: 'classificado', label: 'Classificado', publicDescription: 'O candidato foi classificado conforme os critérios e a ordenação oficial do processo.', color: '#15803d', allowsAppeal: false, terminal: false, whatsappTemplate: 'Olá, {{nome}}. Você foi classificado em {{processo}}. Consulte os detalhes no SIGEC Processos: {{link}}.' },
  { code: 'convocado', label: 'Convocado', publicDescription: 'O candidato foi chamado para preencher uma vaga e deve consultar as orientações e o prazo.', color: '#7c3aed', allowsAppeal: false, terminal: false, whatsappTemplate: 'Olá, {{nome}}. Você foi convocado em {{processo}}. Acesse {{link}} para consultar a vaga e o prazo de resposta.' },
  { code: 'desclassificado', label: 'Desclassificado', publicDescription: 'A candidatura foi desclassificada. O motivo e eventual prazo de recurso estão disponíveis na área do candidato.', color: '#dc2626', allowsAppeal: true, terminal: true, whatsappTemplate: 'Olá, {{nome}}. Houve uma atualização na sua candidatura em {{processo}}. Consulte o resultado e o prazo de recurso: {{link}}.' },
  { code: 'recurso', label: 'Recurso', publicDescription: 'O recurso foi registrado e aguarda análise pela equipe responsável.', color: '#0891b2', allowsAppeal: false, terminal: false, whatsappTemplate: 'Olá, {{nome}}. Seu recurso em {{processo}} foi registrado. Acompanhe a análise em {{link}}.' },
  { code: 'desistente', label: 'Desistente', publicDescription: 'A desistência foi registrada e a candidatura não seguirá para novas etapas.', color: '#64748b', allowsAppeal: false, terminal: true, whatsappTemplate: 'Olá, {{nome}}. Sua desistência em {{processo}} foi registrada. Consulte o comprovante em {{link}}.' },
] as const

export type SigecStageCode = (typeof SIGEC_DEFAULT_STAGES)[number]['code']
